spring:
  application:
    name: leets-project
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:file:./data/mydb;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
jwt:
  secret: GoogleNaverKaKaoLeetsLesGo_!x9#v2Pq7Z$mL@5nKjR*u8W
  access-token-expiration-millis: 1800000    # 30분 (30 * 60 * 1000)
  refresh-token-expiration-millis: 1209600000 # 14일 (14 * 24 * 60 * 60 * 1000)